// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PFDotNetTraining.Data;

namespace PFDotNetTraining.Migrations
{
    [DbContext(typeof(ShelfContext))]
    [Migration("20210611032300_seedData")]
    partial class seedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PFDotNetTraining.Model.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Extension")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsFile")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedAt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Parent")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Item");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "Employer",
                            CreatedDate = "10/06/2021",
                            Extension = ".docx",
                            IsFile = true,
                            ModifiedAt = "10/06/2021",
                            ModifiedBy = "Employer",
                            Name = "Contract",
                            Parent = "root"
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "Employer",
                            CreatedDate = "10/06/2021",
                            IsFile = false,
                            ModifiedAt = "10/06/2021",
                            ModifiedBy = "Employer",
                            Name = "Documents",
                            Parent = "root"
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = "Employee",
                            CreatedDate = "11/06/2021",
                            Extension = ".docx",
                            IsFile = true,
                            ModifiedAt = "11/06/2021",
                            ModifiedBy = "Employee",
                            Name = "Transcipt",
                            Parent = "2"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
